name: Setup YQ
description: Setup YQ in your environment
author: Kevin Tijssen

inputs:
  version: 
    description: "Which version do you want to install?"
    default: 'lastest'

runs:
  using: "composite"
  steps:
    - name: Download YQ from GitHub
      shell: bash
      run: |
        if [[ ${{ inputs.version }} != "latest" ]]; then
          wget https://github.com/mikefarah/yq/releases/download/${{ inputs.version }}/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
        else
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
        fi
    - name: Show installed version
      shell: bash
      run: |
        yq --version